---
  - name: Install Apache
    apt: name=apache2 state=present

  - name: Install PHP Module for Apache
    apt: name=libapache2-mod-php5 state=present update_cache=yes

  - name: Start Apache
    service: name=apache2 state=started enabled=yes
